inherit_from: .rubocop_todo.yml
require:
  - rubocop-thread_safety
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*

Naming/MemoizedInstanceVariableName:
  Exclude:
    - app/controllers/**/*