language: ruby
rvm:
  - 1.9.3
bundler_args: "--without development"
before_script: "./config/before-travis.sh"
script: "export DISPLAY=:99.0 && bundle exec rake"

notifications:
  irc:
    channels:
      - 'irc.freenode.org:6667#railsbridge'
