language: ruby
rvm:
  - 2.0.0
bundler_args: "--without development"
before_script:
  - phantomjs --version
  - ci/install_phantomjs
  - "export PATH=`pwd`/phantomjs/bin:$PATH"
  - phantomjs --version
  - "./config/before-travis.sh"
script: "bundle exec rake && bundle exec rake jasmine:phantom:ci"

notifications:
  email: false
