language: ruby
rvm:
  - 2.0.0
bundler_args: "--without development"
before_script:
  - "./config/before-travis.sh"
script: "bundle exec rake && bundle exec rake jasmine:ci"

notifications:
  email: false
