language: ruby
rvm:
  - 2.6.5
bundler_args: "--without development production --deployment"
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
    - tmp

addons:
  chrome: stable

env:
  global:
    - "PATH=$PWD/node_modules/.bin:$PATH"

matrix:
  include:
  - env: FORCE_POSTGRES=true
    services:
    - postgresql
  - env: DO_NOT_FORCE_POSTGRES=true

before_install:
  - 'env'
  - 'yarn install'
  - 'echo ''gem: --no-document'' > ~/.gemrc'
  - 'gem update --system'
  - 'gem install bundler'
before_script:
  - 'bundle exec rake parallel:setup'
script:
  - 'bundle exec rake'

sudo: false
