language: ruby
rvm:
  - 2.7.1
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
    - tmp

addons:
  chrome: stable

env:
  global:
    - PATH=$PWD/node_modules/.bin:$PATH

matrix:
  include:
    - env: FORCE_POSTGRES=true
      services:
        - postgresql
    - env: DO_NOT_FORCE_POSTGRES=true

before_install:
  - env
  - nvm install 12
  - yarn install
  - google-chrome-stable --version
  - "echo 'gem: --no-document' > ~/.gemrc"
  - gem update --system
  - gem install bundler
  - bundle config set --local deployment 'true'
  - bundle config set --local without 'development production'

before_script:
  - bundle exec rake parallel:setup

sudo: false
